In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant(
    [
        [1, 2, 0],
        [3, 5, -1],
        [1, 5, 6],
        [2, 3, 8],
    ]
)
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([
    [[1, 2, 0], 
     [3, 5, -1]],

     [[10, 2, 0], 
     [1, 0, 2]],

     [[5, 8, 0], 
     [2, 7, 0]], 

    [[2, 1, 9], 
     [4, -3, 32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [6]:
print(tensor_three_d.shape)

(4, 2, 3)


In [7]:
print(tensor_three_d.ndim)

3


In [8]:
tensor_four_d = tf.constant(
    [
        [
            [[1, 2, 0], [3, 5, -1]],
            [[10, 2, 0], [1, 0, 2]],
            [[5, 8, 0], [2, 7, 0]],
            [[2, 1, 9], [4, -3, 32]],
        ],
        [
            [[1, 2, 0], [3, 5, -1]],
            [[10, 2, 0], [1, 0, 2]],
            [[5, 8, 0], [2, 7, 0]],
            [[2, 1, 9], [4, -3, 32]],
        ],
        [
            [[1, 2, 0], [3, 5, -1]],
            [[10, 2, 0], [1, 0, 2]],
            [[5, 8, 0], [2, 7, 0]],
            [[2, 1, 9], [4, -3, 32]],
        ],
    ]
)
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [9]:
#dtype
tensor_one_d = tf.constant([2, 0, -3], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [10]:
#tf.cast(x, dtype=)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int64)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int64)


In [11]:
#tf.cast(x, dtype=tf.bool)
#All positives and negatives become True. 0 becomes False
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [12]:
import numpy as np

In [13]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [14]:
#tf.convert_to_tensor(np_array)
#convert numpy array to tensor
converted_tensor = tf.convert_to_tensor(np_array)

In [15]:
#tf.eye()
#construct identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [16]:
print(4*eye_tensor)

tf.Tensor(
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]], shape=(3, 3), dtype=float32)


In [17]:
# Identity matrix is truncated based on rows and columns
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]
 [False False False]
 [False False False]], shape=(5, 3), dtype=bool)


In [18]:
# Identity matrix in 1D batch shape is multiples of matrix
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=6,
    batch_shape=[2,],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1 0 0 0 0 0]
  [0 1 0 0 0 0]
  [0 0 1 0 0 0]
  [0 0 0 1 0 0]]

 [[1 0 0 0 0 0]
  [0 1 0 0 0 0]
  [0 0 1 0 0 0]
  [0 0 0 1 0 0]]], shape=(2, 4, 6), dtype=int32)


In [19]:
# Identity matrix in nD batch shape of arbitrary dimension 
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=6,
    batch_shape=[2,3],
    dtype=tf.dtypes.int32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1 0 0 0 0 0]
   [0 1 0 0 0 0]
   [0 0 1 0 0 0]
   [0 0 0 1 0 0]]

  [[1 0 0 0 0 0]
   [0 1 0 0 0 0]
   [0 0 1 0 0 0]
   [0 0 0 1 0 0]]

  [[1 0 0 0 0 0]
   [0 1 0 0 0 0]
   [0 0 1 0 0 0]
   [0 0 0 1 0 0]]]


 [[[1 0 0 0 0 0]
   [0 1 0 0 0 0]
   [0 0 1 0 0 0]
   [0 0 0 1 0 0]]

  [[1 0 0 0 0 0]
   [0 1 0 0 0 0]
   [0 0 1 0 0 0]
   [0 0 0 1 0 0]]

  [[1 0 0 0 0 0]
   [0 1 0 0 0 0]
   [0 0 1 0 0 0]
   [0 0 0 1 0 0]]]], shape=(2, 3, 4, 6), dtype=int32)


In [20]:
fill_tensor=tf.fill(
    [3,4], 5, name =None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [21]:
ones_tensor=tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [22]:
#Pass a tensor, get a tensor of ones of similar shape
ones_like_tensor=tf.ones_like(
    fill_tensor,
    dtype=None,
    name=None
)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)
